# Pandas 한 번에 제대로 배우기 - feat. 이수안컴퓨터연구소

## Pandas 객체

In [1]:
import numpy as np
import pandas as pd

pd.__version__

'1.2.4'

### Series 객체

In [2]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0])
# 인덱스를 따로 지정하지 않을 경우 자동으로 정수형 인덱스가 지정된다.
s

0    0.00
1    0.25
2    0.50
3    0.75
4    1.00
dtype: float64

In [3]:
s.values # Series형태에서도 value값만 따로 추출 가능

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [4]:
list(s.values)  # list 형태로도 추출이 가능

[0.0, 0.25, 0.5, 0.75, 1.0]

In [5]:
s.index # Series형태에서도 index값만 따로 추출 가능

RangeIndex(start=0, stop=5, step=1)

In [6]:
s[1] # Slicing 가능

0.25

In [7]:
s[1:4]

1    0.25
2    0.50
3    0.75
dtype: float64

In [8]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index = ['a', 'b', 'c', 'd', 'e'])
# pd.Serires함수에서 index를 지정하면 정수형 index가 아닌 사용자 지정 인덱스 생성이 가능하다.
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [9]:
s['c']

0.5

In [10]:
s[['c', 'd','e']]

c    0.50
d    0.75
e    1.00
dtype: float64

In [11]:
'b' in s

True

In [12]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index = [2, 4, 6, 8, 10])
s

2     0.00
4     0.25
6     0.50
8     0.75
10    1.00
dtype: float64

In [13]:
s[4]

0.25

In [14]:
s[2:]

6     0.50
8     0.75
10    1.00
dtype: float64

In [15]:
s.unique()

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
s.value_counts()

0.00    1
1.00    1
0.50    1
0.75    1
0.25    1
dtype: int64

In [17]:
s.isin([0.25, 0.75]) # 0.25, 0.75가 어디에 존재하는지 boolean으로 출력

2     False
4      True
6     False
8      True
10    False
dtype: bool

In [18]:
s[s.isin([0.25, 0.75])]

4    0.25
8    0.75
dtype: float64

In [19]:
pop_tuple = {'서울특별시': 9720846, 
             '부산광역시': 3404423,
             '인천광역시': 2947217,
             '대구광역시': 2427954,
             '대전광역시': 1471040,
             '광주광역시': 1455048}
population = pd.Series(pop_tuple)
population

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
dtype: int64

In [20]:
population['서울특별시']

9720846

In [21]:
population['서울특별시':'인천광역시'] # 한글 슬라이싱도 가능

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
dtype: int64

### DataFrame 객체

In [22]:
pd.DataFrame([{'A':2, 'B':4, 'D':3},{'A':4, 'B':5, 'C':7}]) # 여러 columns을 가진 2차원 특성을 가짐

A  B    D    C
0  2  4  3.0  NaN
1  4  5  NaN  7.0

In [23]:
pd.DataFrame(np.random.rand(5, 5),
             columns = ['A', 'B', 'C', 'D', 'E'], 
             index = [1, 2, 3, 4, 5])

A         B         C         D         E
1  0.098922  0.592584  0.507958  0.570805  0.836561
2  0.492489  0.379799  0.420120  0.928192  0.350903
3  0.771093  0.944001  0.286620  0.839418  0.154492
4  0.774150  0.308371  0.060260  0.866474  0.962171
5  0.965168  0.545487  0.067496  0.995501  0.941892

In [24]:
male_tuple = {'서울특별시': 4732275, 
              '부산광역시': 1668618,
              '인천광역시': 1476813,
              '대구광역시': 1198815,
              '대전광역시': 734441,
              '광주광역시': 720060}
male = pd.Series(male_tuple)
male

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
dtype: int64

In [25]:
female_tuple = {'서울특별시': 4988571, 
                '부산광역시': 1735805,
                '인천광역시': 1470404,
                '대구광역시': 1229139,
                '대전광역시': 736599,
                '광주광역시': 734988}
female = pd.Series(female_tuple)
# 딕셔너리 형태로도 시리즈를 생성가능
female

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
dtype: int64

In [26]:
korea_df = pd.DataFrame({'인구수':population, 
                         '남자인구수':male,
                         '여자인구수':female})
# 컬럼명과 시리즈를 딕셔너리 형태로 묶어서 데이터 프레임을 만들수 있다.
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [27]:
korea_df.index

Index(['서울특별시', '부산광역시', '인천광역시', '대구광역시', '대전광역시', '광주광역시'], dtype='object')

In [28]:
korea_df.columns

Index(['인구수', '남자인구수', '여자인구수'], dtype='object')

In [29]:
korea_df['여자인구수']

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [30]:
korea_df['서울특별시':'인천광역시']
# 인덱스명으로도 슬라이싱이 가능

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404

In [31]:
korea_df['인구수']

서울특별시    9720846
부산광역시    3404423
인천광역시    2947217
대구광역시    2427954
대전광역시    1471040
광주광역시    1455048
Name: 인구수, dtype: int64

### Index 객체
 
  

|클래스|설명|
|:--|:--|
|Index|일반적은 Index 객체이며, Numpy 배열 형식으로 축의 이름 표현|
|Int64Index|정수 값을 위한 Index|
|MultiIndex|단일 축에 여러 단계 색인을 표현하는 계층적 Index객체(튜플의 배열과 유사)|
|DatetimeIndex|Numpy의 datatime64 타입으로 타임스탬프 저장|
|PeriodIndex|기간 데이터를 위한 Index|

In [32]:
idx = pd.Index([2, 4, 6, 8, 10])
idx

Int64Index([2, 4, 6, 8, 10], dtype='int64')

In [33]:
idx[1]

4

In [34]:
idx[1:2:2]

Int64Index([4], dtype='int64')

In [35]:
idx[-1:]

Int64Index([10], dtype='int64')

In [36]:
idx[::-2]

Int64Index([10, 6, 2], dtype='int64')

In [37]:
print(idx)
print(idx.size)   # 5개의 값이 들어가 있다.
print(idx.shape)  # 1차원 shape
print(idx.ndim)   # 차원 수
print(idx.dtype)  # 데이터 타입

Int64Index([2, 4, 6, 8, 10], dtype='int64')
5
(5,)
1
int64


#### index 연산
|연산자|메소드|설명|
|:-|:-|:-|
||```append```|색인 객체를 추가한 새로운 색인 반환|
||```difference```|색인의 차집합 반환|
|```&```|```intersection```|색인의 교집합 반환|
|```\|```|```union```|색인의 합집합 반환|
||```isin```|색인이 존재하는지 여부를 불리언 배열로 반환|
||```delete```|색인이 삭제된 새로운 색인 반환
||```drop```|값이 삭제된 새로운 색인 반환|
||```insert```|색인이 추가된 새로운 색인 반환|
||```is_monotonic```|색인이 단조성을 가지면 True|
||```is_unique```|중복되는 색인이 없다면 True|
||```unique```|색인에서 중복되는 요소를 제거하고 유일한 값만 반환|

In [38]:
idx1 = pd.Index([1, 2, 4, 6, 8])
idx2 = pd.Index([2, 4, 5, 6, 7])
print(idx1.append(idx2))
print(idx1.difference(idx2))
print(idx1 - idx2)
print(idx1.intersection(idx2))
print(idx1 & idx2 )
print(idx1.union(idx2)) # 중복을 제외함
print(idx1|idx2)
print(idx1.delete(0))   # 인덱스 번호를 지정하여 그 해당하는 번호의 값을 제거
print(idx1.drop(1))     # idx1에 있는 값을 지정하여 그 값을 제거
print(idx1^idx2)        # 공통된 것을 뺀 나머지 (차집합)

Int64Index([1, 2, 4, 6, 8, 2, 4, 5, 6, 7], dtype='int64')
Int64Index([1, 8], dtype='int64')
Int64Index([-1, -2, -1, 0, 1], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([2, 4, 6], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([1, 2, 4, 5, 6, 7, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([2, 4, 6, 8], dtype='int64')
Int64Index([1, 5, 7, 8], dtype='int64')


<ipython-input-38-4abd78589c9d>:7: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  print(idx1 & idx2 )
<ipython-input-38-4abd78589c9d>:9: FutureWarning: Index.__or__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__or__.  Use index.union(other) instead
  print(idx1|idx2)
<ipython-input-38-4abd78589c9d>:12: FutureWarning: Index.__xor__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__xor__.  Use index.symmetric_difference(other) instead
  print(idx1^idx2)        # 공통된 것을 뺀 나머지 (차집합)


## 인덱싱 ( Indexing )

In [39]:
s = pd.Series([0, 0.25, 0.5, 0.75, 1.0],
              index = ['a','b','c','d','e'])
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
dtype: float64

In [40]:
s['b']

0.25

In [41]:
'b' in s

True

In [42]:
s.keys() # 해당하는 인덱스값들을 반환

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [43]:
list(s.items()) # 시리즈의 값들이 tuple 값으로 묶여서 나온다.

[('a', 0.0), ('b', 0.25), ('c', 0.5), ('d', 0.75), ('e', 1.0)]

In [44]:
s['f'] = 1.25
s

a    0.00
b    0.25
c    0.50
d    0.75
e    1.00
f    1.25
dtype: float64

In [45]:
s['a':'d']

a    0.00
b    0.25
c    0.50
d    0.75
dtype: float64

In [46]:
s[0:3]

a    0.00
b    0.25
c    0.50
dtype: float64

In [47]:
s[ (s > 0.4) & (s < 0.8) ] # filtering을 조건으로 주어 인덱싱을 반환이 가능함

c    0.50
d    0.75
dtype: float64

In [48]:
s[['a','c','e']]

a    0.0
c    0.5
e    1.0
dtype: float64

### Series 인덱싱

In [49]:
s = pd.Series(['a', 'b', 'c', 'd', 'e'],
              index=[1, 3, 5, 7, 9])
s

1    a
3    b
5    c
7    d
9    e
dtype: object

In [50]:
s[1]

'a'

In [51]:
s[2:4]

5    c
7    d
dtype: object

In [52]:
s.iloc[1]

'b'

In [53]:
s.iloc[2:4]

5    c
7    d
dtype: object

In [54]:
s.reindex(range(10))
# reindex를 하면 index를 생성시키며 없는 값은 NaN값으로 반환함

0    NaN
1      a
2    NaN
3      b
4    NaN
5      c
6    NaN
7      d
8    NaN
9      e
dtype: object

In [55]:
s.reindex(range(10), method='bfill') # '그 전값으로 NaN 값을 채워줘'라는 메소드

0    a
1    a
2    b
3    b
4    c
5    c
6    d
7    d
8    e
9    e
dtype: object

### DataFrame 인덱싱

|사용방법|설명|
|:-|:-|
|```df[val]```|하나의 컬럼 또는 여러 컬럼을 선택|
|```df.loc[val]```|레이블 값으로 로우의 부분집합 선택|
|```df.loc[:,val]```|레이블 값으로 컬럼의 부분집합 선택|
|```df.loc[val1, val2]```|레이블 값으로 로우와 컬럼의 부분집합 선택|
|```df.iloc[where]```|정수 색인으로 로우의 부분집합 선택|
|```df.iloc[:,where]```|정수 색인으로 컬럼의 부분집합 선택|
|```df.iloc[where_i,where_j]```|정수 색인으로 로우와 컬럼의 부분집합 선택|
|```df.at[label_i,label_j]```|로우와 컬럼의 라벨로 단일 값 선택|
|```df.iat[i, j]```|로우와 컬럼의 정수 색인으로 단일 값 선택|
|```reindex```|하나 이상의 축을 새로운 색인으로 재색인|
|```get_value, set_value```|로우와 컬럼의 이름으로 값 선택|

In [56]:
korea_df

인구수    남자인구수    여자인구수
서울특별시  9720846  4732275  4988571
부산광역시  3404423  1668618  1735805
인천광역시  2947217  1476813  1470404
대구광역시  2427954  1198815  1229139
대전광역시  1471040   734441   736599
광주광역시  1455048   720060   734988

In [57]:
korea_df.at['부산광역시','인구수']
# at은 어떠한 특정한 조건에 맞는 단일 값을 가져오는데 사용함
# 첫번째 인자값으로 index를, 두번째 인자값으로 column을 가져온다.

3404423

In [58]:
korea_df['남자인구수']

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [59]:
korea_df.남자인구수

서울특별시    4732275
부산광역시    1668618
인천광역시    1476813
대구광역시    1198815
대전광역시     734441
광주광역시     720060
Name: 남자인구수, dtype: int64

In [60]:
korea_df.여자인구수

서울특별시    4988571
부산광역시    1735805
인천광역시    1470404
대구광역시    1229139
대전광역시     736599
광주광역시     734988
Name: 여자인구수, dtype: int64

In [61]:
korea_df['남여비율'] = (korea_df.남자인구수 * 100 / korea_df.여자인구수 ) 
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [62]:
korea_df.values # korea_df의 모든 값들을 반환함

array([[9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01],
       [3.40442300e+06, 1.66861800e+06, 1.73580500e+06, 9.61293463e+01],
       [2.94721700e+06, 1.47681300e+06, 1.47040400e+06, 1.00435867e+02],
       [2.42795400e+06, 1.19881500e+06, 1.22913900e+06, 9.75329072e+01],
       [1.47104000e+06, 7.34441000e+05, 7.36599000e+05, 9.97070319e+01],
       [1.45504800e+06, 7.20060000e+05, 7.34988000e+05, 9.79689464e+01]])

In [63]:
korea_df.values[0]  # values의 첫번째 값 (서울특별시)만 가져옴

array([9.72084600e+06, 4.73227500e+06, 4.98857100e+06, 9.48623363e+01])

In [64]:
korea_df.T  # 기존의 행과 열의 순서를 바꿈

서울특별시         부산광역시         인천광역시         대구광역시         대전광역시  \
인구수    9.720846e+06  3.404423e+06  2.947217e+06  2.427954e+06  1.471040e+06   
남자인구수  4.732275e+06  1.668618e+06  1.476813e+06  1.198815e+06  7.344410e+05   
여자인구수  4.988571e+06  1.735805e+06  1.470404e+06  1.229139e+06  7.365990e+05   
남여비율   9.486234e+01  9.612935e+01  1.004359e+02  9.753291e+01  9.970703e+01   

              광주광역시  
인구수    1.455048e+06  
남자인구수  7.200600e+05  
여자인구수  7.349880e+05  
남여비율   9.796895e+01

In [65]:
korea_df.loc[:'인천광역시', :'남자인구수']

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

In [66]:
korea_df.loc[ (korea_df.여자인구수 > 1000000) ]
# loc안에 조건으로 filter를 넣으면 그에 맞는 row값으로 반환이 됌

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907

In [67]:
korea_df.loc[ (korea_df.인구수 < 2000000) ]

인구수   남자인구수   여자인구수       남여비율
대전광역시  1471040  734441  736599  99.707032
광주광역시  1455048  720060  734988  97.968946

In [68]:
korea_df.loc[ (korea_df.인구수 > 2500000) ]

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867

In [69]:
korea_df.loc[ korea_df.남여비율 > 100 ]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [70]:
korea_df.loc[ ( korea_df.인구수 > 2500000 ) & ( korea_df.남여비율 > 100 )]

인구수    남자인구수    여자인구수        남여비율
인천광역시  2947217  1476813  1470404  100.435867

In [71]:
korea_df.iloc[:3, :2]

인구수    남자인구수
서울특별시  9720846  4732275
부산광역시  3404423  1668618
인천광역시  2947217  1476813

### 다중 인덱스( Multi Indexing )
- 1차원의 Series와 2차원의 DataFrame 객체를 넘어 3차원, 4차원 이상의 고차원 데이터 처리
- 단일 인덱스 내에 여러 인덱스를 포함하는 다중 인덱싱

#### 다중 인덱스 Series

In [72]:
korea_df

인구수    남자인구수    여자인구수        남여비율
서울특별시  9720846  4732275  4988571   94.862336
부산광역시  3404423  1668618  1735805   96.129346
인천광역시  2947217  1476813  1470404  100.435867
대구광역시  2427954  1198815  1229139   97.532907
대전광역시  1471040   734441   736599   99.707032
광주광역시  1455048   720060   734988   97.968946

In [73]:
idx_tuples = [('서울특별시', 2010), ('서울특별시',2020),
              ('부산광역시', 2010), ('부산광역시',2020),
              ('인천광역시', 2010), ('인천광역시',2020),
              ('대구광역시', 2010), ('대구광역시',2020),
              ('대전광역시', 2010), ('대전광역시',2020),
              ('광주광역시', 2010), ('광주광역시',2020),
             ]
idx_tuples

[('서울특별시', 2010),
 ('서울특별시', 2020),
 ('부산광역시', 2010),
 ('부산광역시', 2020),
 ('인천광역시', 2010),
 ('인천광역시', 2020),
 ('대구광역시', 2010),
 ('대구광역시', 2020),
 ('대전광역시', 2010),
 ('대전광역시', 2020),
 ('광주광역시', 2010),
 ('광주광역시', 2020)]

In [74]:
pop_tuples = [10312545, 9720846,
              2567910, 3404423,
              2758296, 2847217,
              2511676, 2427954,
              1503664, 1471040,
              1454636, 1455048]
population = pd.Series(pop_tuples, index = idx_tuples)
population

(서울특별시, 2010)    10312545
(서울특별시, 2020)     9720846
(부산광역시, 2010)     2567910
(부산광역시, 2020)     3404423
(인천광역시, 2010)     2758296
(인천광역시, 2020)     2847217
(대구광역시, 2010)     2511676
(대구광역시, 2020)     2427954
(대전광역시, 2010)     1503664
(대전광역시, 2020)     1471040
(광주광역시, 2010)     1454636
(광주광역시, 2020)     1455048
dtype: int64

In [75]:
midx = pd.MultiIndex.from_tuples(idx_tuples)
midx

MultiIndex([('서울특별시', 2010),
            ('서울특별시', 2020),
            ('부산광역시', 2010),
            ('부산광역시', 2020),
            ('인천광역시', 2010),
            ('인천광역시', 2020),
            ('대구광역시', 2010),
            ('대구광역시', 2020),
            ('대전광역시', 2010),
            ('대전광역시', 2020),
            ('광주광역시', 2010),
            ('광주광역시', 2020)],
           )

In [76]:
population = population.reindex(midx)
population

서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2847217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [77]:
population[:, 2010]

서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [78]:
population['대전광역시',:]

2010    1503664
2020    1471040
dtype: int64

In [79]:
korea_mdf = population.unstack()  # MutiIndex를 DataFrame 형태로 변환함
korea_mdf

2010     2020
광주광역시   1454636  1455048
대구광역시   2511676  2427954
대전광역시   1503664  1471040
부산광역시   2567910  3404423
서울특별시  10312545  9720846
인천광역시   2758296  2847217

In [80]:
korea_mdf.stack()

광주광역시  2010     1454636
       2020     1455048
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
부산광역시  2010     2567910
       2020     3404423
서울특별시  2010    10312545
       2020     9720846
인천광역시  2010     2758296
       2020     2847217
dtype: int64

In [81]:
male_tuple = [5111259, 4732275,
              1773170, 1668618, 
              1390356, 1476813, 
              1255245, 1198815, 
              753648, 734441, 
              721780, 720060]

male_tuple

[5111259,
 4732275,
 1773170,
 1668618,
 1390356,
 1476813,
 1255245,
 1198815,
 753648,
 734441,
 721780,
 720060]

In [82]:
population.index.names = ['행정구역','년도']
korea_mdf = pd.DataFrame({'총인구수':population,
                          '남자인구수':male_tuple})

korea_mdf

총인구수    남자인구수
행정구역  년도                     
서울특별시 2010  10312545  5111259
      2020   9720846  4732275
부산광역시 2010   2567910  1773170
      2020   3404423  1668618
인천광역시 2010   2758296  1390356
      2020   2847217  1476813
대구광역시 2010   2511676  1255245
      2020   2427954  1198815
대전광역시 2010   1503664   753648
      2020   1471040   734441
광주광역시 2010   1454636   721780
      2020   1455048   720060

In [83]:
female_tuples = [5201286, 4988571,
                1794740, 1735805,
                1367940, 1470404,
                1256431, 1229139,
                750016, 736599,
                732956, 734988]

In [84]:
korea_mdf = pd.DataFrame({'총인구수':population,
                          '남자인구수':male_tuple,
                          '여자인구수':female_tuples})
korea_mdf

총인구수    남자인구수    여자인구수
행정구역  년도                              
서울특별시 2010  10312545  5111259  5201286
      2020   9720846  4732275  4988571
부산광역시 2010   2567910  1773170  1794740
      2020   3404423  1668618  1735805
인천광역시 2010   2758296  1390356  1367940
      2020   2847217  1476813  1470404
대구광역시 2010   2511676  1255245  1256431
      2020   2427954  1198815  1229139
대전광역시 2010   1503664   753648   750016
      2020   1471040   734441   736599
광주광역시 2010   1454636   721780   732956
      2020   1455048   720060   734988

In [85]:
ratio = korea_mdf['남자인구수'] * 100 / korea_mdf['여자인구수']
ratio

행정구역   년도  
서울특별시  2010     98.269140
       2020     94.862336
부산광역시  2010     98.798155
       2020     96.129346
인천광역시  2010    101.638668
       2020    100.435867
대구광역시  2010     99.905606
       2020     97.532907
대전광역시  2010    100.484256
       2020     99.707032
광주광역시  2010     98.475215
       2020     97.968946
dtype: float64

In [86]:
ratio.unstack()

년도           2010        2020
행정구역                         
광주광역시   98.475215   97.968946
대구광역시   99.905606   97.532907
대전광역시  100.484256   99.707032
부산광역시   98.798155   96.129346
서울특별시   98.269140   94.862336
인천광역시  101.638668  100.435867

In [87]:
korea_mdf = pd.DataFrame({'총인구수':population,
                          '남자인구수':male_tuple,
                          '여자인구수':female_tuples,
                          '남녀비율':ratio})
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2847217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732956   98.475215
      2020   1455048   720060   734988   97.968946

#### 다중 인덱스 생성

In [88]:
df = pd.DataFrame(np.random.rand(6, 3),
                  index=[['a','a','b','b','c','c'], [1, 2, 1, 2, 1, 2]],
                  columns = ['c1', 'c2','c3'])
df

c1        c2        c3
a 1  0.330843  0.825188  0.188806
  2  0.816854  0.345297  0.161200
b 1  0.419148  0.922844  0.577177
  2  0.018861  0.298965  0.729026
c 1  0.610798  0.734315  0.840874
  2  0.881636  0.253515  0.480008

In [89]:
pd.MultiIndex.from_arrays([['a','a','b','b','c','c'], [1, 2, 1, 2, 1, 2]])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [90]:
pd.MultiIndex.from_tuples([('a',1),('a',2),('b',1),('b',2),('c',1),('c',2)])

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [91]:
pd.MultiIndex.from_product([['a','b','c'], [1, 2]])  # 처음 []값과 다음 []값을 곱해라
                                                     # ex) ['a'] [1] , ['a'] [2] / ['b'] [1], ['b'] [2] / ...

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [92]:
pd.MultiIndex(levels=[['a','b','c'],[1,2]],                  
              codes=[[0, 0, 1, 1, 2, 2],[0, 1, 0, 1, 0, 1]]) # 인덱스의 번호를 나열하여 멀티인덱스를 생성

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           )

In [93]:
population.index.names = ['행정구역','년도']
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2847217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [94]:
idx = pd.MultiIndex.from_product([['a', 'b','c'],[1,2]],
                                 names = ['name1','name2'])
cols = pd.MultiIndex.from_product([['c1','c2','c3'], [1, 2]],
                                  names = ['col_name1','col_name2'])
data = np.round(np.random.randn(6, 6),2)
mdf = pd.DataFrame(data, index=idx, columns=cols)
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.70 -0.26 -0.24  0.09 -1.11  1.02
      2      2.17  0.39 -0.31 -0.10  1.14 -1.54
b     1     -0.36 -0.04  0.84 -0.26  0.76  0.35
      2     -1.84  1.83 -0.81  1.42 -0.08  0.07
c     1      0.82  0.11  0.47 -0.14 -0.98 -0.29
      2      1.20 -0.35 -0.24 -0.92 -0.07 -0.65

In [95]:
mdf['c2']

col_name2       1     2
name1 name2            
a     1     -0.24  0.09
      2     -0.31 -0.10
b     1      0.84 -0.26
      2     -0.81  1.42
c     1      0.47 -0.14
      2     -0.24 -0.92

#### 인덱싱 및 슬라이싱

In [96]:
population

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2010     2567910
       2020     3404423
인천광역시  2010     2758296
       2020     2847217
대구광역시  2010     2511676
       2020     2427954
대전광역시  2010     1503664
       2020     1471040
광주광역시  2010     1454636
       2020     1455048
dtype: int64

In [97]:
population['인천광역시', 2010]

2758296

In [98]:
population[:,2010]

행정구역
서울특별시    10312545
부산광역시     2567910
인천광역시     2758296
대구광역시     2511676
대전광역시     1503664
광주광역시     1454636
dtype: int64

In [99]:
population[ population > 3000000 ]

행정구역   년도  
서울특별시  2010    10312545
       2020     9720846
부산광역시  2020     3404423
dtype: int64

In [100]:
population[['대구광역시','대전광역시']]

행정구역   년도  
대구광역시  2010    2511676
       2020    2427954
대전광역시  2010    1503664
       2020    1471040
dtype: int64

In [101]:
mdf

col_name1      c1          c2          c3      
col_name2       1     2     1     2     1     2
name1 name2                                    
a     1     -0.70 -0.26 -0.24  0.09 -1.11  1.02
      2      2.17  0.39 -0.31 -0.10  1.14 -1.54
b     1     -0.36 -0.04  0.84 -0.26  0.76  0.35
      2     -1.84  1.83 -0.81  1.42 -0.08  0.07
c     1      0.82  0.11  0.47 -0.14 -0.98 -0.29
      2      1.20 -0.35 -0.24 -0.92 -0.07 -0.65

In [102]:
mdf['c2',1]

name1  name2
a      1       -0.24
       2       -0.31
b      1        0.84
       2       -0.81
c      1        0.47
       2       -0.24
Name: (c2, 1), dtype: float64

In [103]:
mdf.iloc[:3, :4]

col_name1      c1          c2      
col_name2       1     2     1     2
name1 name2                        
a     1     -0.70 -0.26 -0.24  0.09
      2      2.17  0.39 -0.31 -0.10
b     1     -0.36 -0.04  0.84 -0.26

In [104]:
mdf.loc[:,('c2',1)]

name1  name2
a      1       -0.24
       2       -0.31
b      1        0.84
       2       -0.81
c      1        0.47
       2       -0.24
Name: (c2, 1), dtype: float64

In [105]:
idx_slice = pd.IndexSlice
mdf.loc[idx_slice[:,2], idx_slice[:,2]]

col_name1      c1    c2    c3
col_name2       2     2     2
name1 name2                  
a     2      0.39 -0.10 -1.54
b     2      1.83  1.42  0.07
c     2     -0.35 -0.92 -0.65

#### 다중 인덱스 재정렬

In [106]:
idx

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('c', 1),
            ('c', 2)],
           names=['name1', 'name2'])

In [107]:
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2847217  1476813  1470404  100.435867
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
광주광역시 2010   1454636   721780   732956   98.475215
      2020   1455048   720060   734988   97.968946

In [108]:
# korea_mdf['서울특별시':'인천광역시'] 
# 멀티인덱스는 초기 인덱스가 정렬이 되어 있지 않기 때문에 단순히 슬라이싱을 하면 에러가 나타난다

korea_mdf = korea_mdf.sort_index()
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732956   98.475215
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2847217  1476813  1470404  100.435867

In [109]:
korea_mdf['서울특별시':'인천광역시']

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2847217  1476813  1470404  100.435867

In [110]:
korea_mdf.unstack(level=0)
# level 조정을 통해 연도와 시군구를 switch할 수 있다.

총인구수                                                 남자인구수           \
행정구역    광주광역시    대구광역시    대전광역시    부산광역시     서울특별시    인천광역시   광주광역시    대구광역시   
년도                                                                             
2010  1454636  2511676  1503664  2567910  10312545  2758296  721780  1255245   
2020  1455048  2427954  1471040  3404423   9720846  2847217  720060  1198815   

                       ...   여자인구수                                  남녀비율  \
행정구역   대전광역시    부산광역시  ...   대전광역시    부산광역시    서울특별시    인천광역시      광주광역시   
년도                     ...                                                 
2010  753648  1773170  ...  750016  1794740  5201286  1367940  98.475215   
2020  734441  1668618  ...  736599  1735805  4988571  1470404  97.968946   

                                                               
행정구역      대구광역시       대전광역시      부산광역시      서울특별시       인천광역시  
년도                                                             
2010  99.905606  100.484256  98.798155  98.269140  101.638668  
2020  97.532907   99.707032  96.129346  94.862336  100.435867  

[2 rows x 24 columns]

In [111]:
korea_mdf.unstack(level=1)

총인구수             남자인구수             여자인구수                 남녀비율  \
년도         2010     2020     2010     2020     2010     2020        2010   
행정구역                                                                       
광주광역시   1454636  1455048   721780   720060   732956   734988   98.475215   
대구광역시   2511676  2427954  1255245  1198815  1256431  1229139   99.905606   
대전광역시   1503664  1471040   753648   734441   750016   736599  100.484256   
부산광역시   2567910  3404423  1773170  1668618  1794740  1735805   98.798155   
서울특별시  10312545  9720846  5111259  4732275  5201286  4988571   98.269140   
인천광역시   2758296  2847217  1390356  1476813  1367940  1470404  101.638668   

                   
년도           2020  
행정구역               
광주광역시   97.968946  
대구광역시   97.532907  
대전광역시   99.707032  
부산광역시   96.129346  
서울특별시   94.862336  
인천광역시  100.435867

In [112]:
korea_mdf.stack()

행정구역   년도         
광주광역시  2010  총인구수     1.454636e+06
             남자인구수    7.217800e+05
             여자인구수    7.329560e+05
             남녀비율     9.847522e+01
       2020  총인구수     1.455048e+06
             남자인구수    7.200600e+05
             여자인구수    7.349880e+05
             남녀비율     9.796895e+01
대구광역시  2010  총인구수     2.511676e+06
             남자인구수    1.255245e+06
             여자인구수    1.256431e+06
             남녀비율     9.990561e+01
       2020  총인구수     2.427954e+06
             남자인구수    1.198815e+06
             여자인구수    1.229139e+06
             남녀비율     9.753291e+01
대전광역시  2010  총인구수     1.503664e+06
             남자인구수    7.536480e+05
             여자인구수    7.500160e+05
             남녀비율     1.004843e+02
       2020  총인구수     1.471040e+06
             남자인구수    7.344410e+05
             여자인구수    7.365990e+05
             남녀비율     9.970703e+01
부산광역시  2010  총인구수     2.567910e+06
             남자인구수    1.773170e+06
             여자인구수    1.794740e+06
             남녀비율     9.879815e+01
 

In [113]:
korea_mdf

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732956   98.475215
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2847217  1476813  1470404  100.435867

In [114]:
idx_flat = korea_mdf.reset_index(level=0)
idx_flat

행정구역      총인구수    남자인구수    여자인구수        남녀비율
년도                                                 
2010  광주광역시   1454636   721780   732956   98.475215
2020  광주광역시   1455048   720060   734988   97.968946
2010  대구광역시   2511676  1255245  1256431   99.905606
2020  대구광역시   2427954  1198815  1229139   97.532907
2010  대전광역시   1503664   753648   750016  100.484256
2020  대전광역시   1471040   734441   736599   99.707032
2010  부산광역시   2567910  1773170  1794740   98.798155
2020  부산광역시   3404423  1668618  1735805   96.129346
2010  서울특별시  10312545  5111259  5201286   98.269140
2020  서울특별시   9720846  4732275  4988571   94.862336
2010  인천광역시   2758296  1390356  1367940  101.638668
2020  인천광역시   2847217  1476813  1470404  100.435867

In [115]:
idx_flat = korea_mdf.reset_index(level=(0,1))
idx_flat

행정구역    년도      총인구수    남자인구수    여자인구수        남녀비율
0   광주광역시  2010   1454636   721780   732956   98.475215
1   광주광역시  2020   1455048   720060   734988   97.968946
2   대구광역시  2010   2511676  1255245  1256431   99.905606
3   대구광역시  2020   2427954  1198815  1229139   97.532907
4   대전광역시  2010   1503664   753648   750016  100.484256
5   대전광역시  2020   1471040   734441   736599   99.707032
6   부산광역시  2010   2567910  1773170  1794740   98.798155
7   부산광역시  2020   3404423  1668618  1735805   96.129346
8   서울특별시  2010  10312545  5111259  5201286   98.269140
9   서울특별시  2020   9720846  4732275  4988571   94.862336
10  인천광역시  2010   2758296  1390356  1367940  101.638668
11  인천광역시  2020   2847217  1476813  1470404  100.435867

In [116]:
idx_flat.set_index(['행정구역', '년도'])

총인구수    남자인구수    여자인구수        남녀비율
행정구역  년도                                          
광주광역시 2010   1454636   721780   732956   98.475215
      2020   1455048   720060   734988   97.968946
대구광역시 2010   2511676  1255245  1256431   99.905606
      2020   2427954  1198815  1229139   97.532907
대전광역시 2010   1503664   753648   750016  100.484256
      2020   1471040   734441   736599   99.707032
부산광역시 2010   2567910  1773170  1794740   98.798155
      2020   3404423  1668618  1735805   96.129346
서울특별시 2010  10312545  5111259  5201286   98.269140
      2020   9720846  4732275  4988571   94.862336
인천광역시 2010   2758296  1390356  1367940  101.638668
      2020   2847217  1476813  1470404  100.435867

## 데이터 연산

In [117]:
s = pd.Series(np.random.randint(0, 10, 5))
s

0    2
1    2
2    9
3    5
4    6
dtype: int32

In [118]:
df = pd.DataFrame(np.random.randint(0, 10, (3, 3)),
                  columns=['A','B','C'])
df

A  B  C
0  6  2  5
1  2  3  3
2  0  4  7

In [119]:
np.exp(s)

0       7.389056
1       7.389056
2    8103.083928
3     148.413159
4     403.428793
dtype: float64

In [120]:
np.cos(df * np.pi / 4)

A             B         C
0 -1.836970e-16  6.123234e-17 -0.707107
1  6.123234e-17 -7.071068e-01 -0.707107
2  1.000000e+00 -1.000000e+00  0.707107

In [121]:
s1 = pd.Series([1, 3, 5, 7, 9], index = [0, 1, 2, 3, 4])
s2 = pd.Series([2, 4, 6, 8, 10], index = [1, 2, 3, 4, 5])
# 데이터 연산을 할때 기준은 index순이기 때문에 index가 일치하지 않는 부분은 NaN으로 나옴
s1+s2

0     NaN
1     5.0
2     9.0
3    13.0
4    17.0
5     NaN
dtype: float64

In [122]:
s1.add(s2, fill_value=0)
# fill_value로 NaN값을 채울 수 있다
# index 0번이 1인 이유는 s1.index(0)의 값이 1이고 s2.index(0)값이 NaN이여서 0으로 채워졌기 때문에
# 그 둘을 합했을 때 1이기 떄문이다.

0     1.0
1     5.0
2     9.0
3    13.0
4    17.0
5    10.0
dtype: float64

In [123]:
df1 = pd.DataFrame(np.random.randint(0, 20, (3, 3)),
                  columns=list('ACD'))
df1

A   C   D
0  18  15  19
1   7  17   1
2   8   5  18

In [124]:
df2 = pd.DataFrame(np.random.randint(0, 20, (5,5)),
                  columns=list('BAECD'))
df2

B   A   E   C  D
0   3  14  14  16  0
1  13  10   0  12  2
2  16  15  16   2  2
3  18  15  12   7  6
4  18  15   0   4  5

In [125]:
df1 + df2

A   B     C     D   E
0  32.0 NaN  31.0  19.0 NaN
1  17.0 NaN  29.0   3.0 NaN
2  23.0 NaN   7.0  20.0 NaN
3   NaN NaN   NaN   NaN NaN
4   NaN NaN   NaN   NaN NaN

In [126]:
fvalue = df1.stack().mean()
# DataFrame을 stack을 하면 Series형태로 변환이 된다.
df1.add(df2, fill_value=fvalue)

A     B     C     D     E
0  32.0  15.0  31.0  19.0  26.0
1  17.0  25.0  29.0   3.0  12.0
2  23.0  28.0   7.0  20.0  28.0
3  27.0  30.0  19.0  18.0  24.0
4  27.0  30.0  16.0  17.0  12.0

### 연산자 범용 함수
|Python 연산자|Pandas 메소드|
|:--|:--|
|```+```|```add```, ```radd```|
|```-```|```sub```,  ```rsub```, ```subtract```|
|```*```|```mul```, ```rmul```, ```multiply```|
|```/```|```truediv```,  ```div```, ```rdiv```, ```divide```|
|```//```|```floordiv```, ```rfloordiv```|
|```%```|```mod```|
|```**```|```pow```, ```rpow```|

#### add( )

In [127]:
a = np.random.randint(1, 10, size=(3, 3))
a

array([[4, 2, 9],
       [4, 5, 6],
       [9, 6, 7]])

In [128]:
a + a[0]

array([[ 8,  4, 18],
       [ 8,  7, 15],
       [13,  8, 16]])

In [129]:
df = pd.DataFrame(a, columns = list('ABC'))
df

A  B  C
0  4  2  9
1  4  5  6
2  9  6  7

In [130]:
df + df.iloc[0]
# pandas 또한 numpy와 같이 크기가 다른 형태의 DataFrame을 더했을때
# 자동적으로 Broadcast되어 계산이 된다.

A  B   C
0   8  4  18
1   8  7  15
2  13  8  16

In [131]:
df.add(df.iloc[0])

A  B   C
0   8  4  18
1   8  7  15
2  13  8  16

#### sub( ) / subtract( )

In [132]:
a

array([[4, 2, 9],
       [4, 5, 6],
       [9, 6, 7]])

In [133]:
a - a[0]

array([[ 0,  0,  0],
       [ 0,  3, -3],
       [ 5,  4, -2]])

In [134]:
df

A  B  C
0  4  2  9
1  4  5  6
2  9  6  7

In [135]:
df - df.iloc[0]

A  B  C
0  0  0  0
1  0  3 -3
2  5  4 -2

In [136]:
df.sub(df.iloc[0])

A  B  C
0  0  0  0
1  0  3 -3
2  5  4 -2

In [137]:
df.subtract(df['B'], axis=0)

A  B  C
0  2  0  7
1 -1  0  1
2  3  0  1

#### mul( ) / multply( )

In [138]:
a

array([[4, 2, 9],
       [4, 5, 6],
       [9, 6, 7]])

In [139]:
a * a[1]

array([[16, 10, 54],
       [16, 25, 36],
       [36, 30, 42]])

In [140]:
df

A  B  C
0  4  2  9
1  4  5  6
2  9  6  7

In [141]:
df * df.iloc[1]

A   B   C
0  16  10  54
1  16  25  36
2  36  30  42

In [142]:
df.mul(df.iloc[1])

A   B   C
0  16  10  54
1  16  25  36
2  36  30  42

In [143]:
df.multiply(df.iloc[2])

A   B   C
0  36  12  63
1  36  30  42
2  81  36  49

#### truediv( ) / div( ) / divide( ) / floordiv( )

In [144]:
a 

array([[4, 2, 9],
       [4, 5, 6],
       [9, 6, 7]])

In [145]:
a / a[0]

array([[1.        , 1.        , 1.        ],
       [1.        , 2.5       , 0.66666667],
       [2.25      , 3.        , 0.77777778]])

In [146]:
df / df.iloc[0]

A    B         C
0  1.00  1.0  1.000000
1  1.00  2.5  0.666667
2  2.25  3.0  0.777778

In [147]:
df.truediv(df.iloc[0])

A    B         C
0  1.00  1.0  1.000000
1  1.00  2.5  0.666667
2  2.25  3.0  0.777778

In [148]:
df.div(df.iloc[0])

A    B         C
0  1.00  1.0  1.000000
1  1.00  2.5  0.666667
2  2.25  3.0  0.777778

In [149]:
df.divide(df.iloc[0])

A    B         C
0  1.00  1.0  1.000000
1  1.00  2.5  0.666667
2  2.25  3.0  0.777778

In [150]:
a // a[0]

array([[1, 1, 1],
       [1, 2, 0],
       [2, 3, 0]], dtype=int32)

In [151]:
df.floordiv(df.iloc[0])

A  B  C
0  1  1  1
1  1  2  0
2  2  3  0

#### mod( )

In [152]:
a

array([[4, 2, 9],
       [4, 5, 6],
       [9, 6, 7]])

In [153]:
a % a[0]

array([[0, 0, 0],
       [0, 1, 6],
       [1, 0, 7]], dtype=int32)

In [154]:
df

A  B  C
0  4  2  9
1  4  5  6
2  9  6  7

In [155]:
df.mod(df.iloc[0])

A  B  C
0  0  0  0
1  0  1  6
2  1  0  7

#### pow( )

In [156]:
a ** a[0]

array([[      256,         4, 387420489],
       [      256,        25,  10077696],
       [     6561,        36,  40353607]], dtype=int32)

In [157]:
df.pow(df.iloc[0])

A   B          C
0   256   4  387420489
1   256  25   10077696
2  6561  36   40353607

In [158]:
row = df.iloc[0, ::2]
row

A    4
C    9
Name: 0, dtype: int32

In [159]:
df - row

A   B    C
0  0.0 NaN  0.0
1  0.0 NaN -3.0
2  5.0 NaN -2.0

### 정렬(Sort)

In [160]:
s = pd.Series(range(5), index=['A','D','B','C','E'])
s

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [161]:
s.sort_index()

A    0
B    2
C    3
D    1
E    4
dtype: int64

In [162]:
s.sort_values()

A    0
D    1
B    2
C    3
E    4
dtype: int64

In [163]:
df = pd.DataFrame(np.random.randint(0, 10, (4, 4)), 
                  index = [2, 4, 1, 3], 
                  columns=list('BDAC'))
df

B  D  A  C
2  2  1  4  4
4  3  3  7  5
1  7  5  5  2
3  3  1  0  2

In [164]:
df.sort_index()

B  D  A  C
1  7  5  5  2
2  2  1  4  4
3  3  1  0  2
4  3  3  7  5

In [165]:
df.sort_index(axis=1)

A  B  C  D
2  4  2  4  1
4  7  3  5  3
1  5  7  2  5
3  0  3  2  1

In [166]:
df.sort_values(by='A')

B  D  A  C
3  3  1  0  2
2  2  1  4  4
1  7  5  5  2
4  3  3  7  5

In [167]:
df.sort_values(by=['A','C'])

B  D  A  C
3  3  1  0  2
2  2  1  4  4
1  7  5  5  2
4  3  3  7  5

### 순위(Ranking)
|메소드|설명|
|:--|:--|
|```average```|기본값. 순위에 같은 값을 가지는 항목들의 평균값을 사용|
|```min```|같은 값을 가지는 그룹을 낮은 순위로 지정|
|```max```|같은 값을 가지는 그룹을 높은 순위로 지정|
|```first```|데이터 내의 위치에 따라 순위 지정|
|```dense```|같은 그룹 내에서 모두 같은 순위를 적용하지 않고 1씩 증가|

In [168]:
s = pd.Series([-2, 4, 7, 3, 0, 7, 5, -4, 2, 6])
s

0   -2
1    4
2    7
3    3
4    0
5    7
6    5
7   -4
8    2
9    6
dtype: int64

In [169]:
s.rank()
# 동일 값인 7이 9.5등으로 동일하게 나와있음

0    2.0
1    6.0
2    9.5
3    5.0
4    3.0
5    9.5
6    7.0
7    1.0
8    4.0
9    8.0
dtype: float64

In [170]:
s.rank(method='first')
# first는 데이터 내의 위치에 따라 순위가 지정되기 때문에 더 빨리 나온 2번 index에 있는 7이 9등이 된다.

0     2.0
1     6.0
2     9.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [171]:
s.rank(method='max')

0     2.0
1     6.0
2    10.0
3     5.0
4     3.0
5    10.0
6     7.0
7     1.0
8     4.0
9     8.0
dtype: float64

In [172]:
s.sort_values(inplace=True)
print(s)
s.rank()

7   -4
0   -2
4    0
8    2
3    3
1    4
6    5
9    6
2    7
5    7
dtype: int64


7    1.0
0    2.0
4    3.0
8    4.0
3    5.0
1    6.0
6    7.0
9    8.0
2    9.5
5    9.5
dtype: float64

### 고성능 연산

In [173]:
nrows, ncols = 100000, 100

df1, df2, df3, df4 = (pd.DataFrame(np.random.rand(nrows, ncols)) for i in range(4))

In [174]:
%timeit df1 + df2 + df3 + df4

205 ms ± 33 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [175]:
%timeit pd.eval('df1 + df2 + df3 + df4')

75.9 ms ± 7.06 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [176]:
%timeit df1 * -df2 / (-df3 * df4)

304 ms ± 94.8 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [177]:
%timeit pd.eval('df1 * -df2 / (-df3 * df4)')

109 ms ± 26.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [178]:
%timeit (df1 < df2) & (df2 <= df3 ) & (df3 != df4)

152 ms ± 18 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [179]:
%timeit pd.eval('(df1 < df2) & (df2 <= df3 ) & (df3 != df4)')

64.8 ms ± 12.6 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [180]:
df = pd.DataFrame(np.random.rand(1000000, 5), columns=['A','B','C','D','E'])
df.head()

A         B         C         D         E
0  0.447120  0.704714  0.824506  0.266879  0.145419
1  0.570413  0.658671  0.559462  0.884593  0.434366
2  0.227988  0.258697  0.012942  0.860729  0.515783
3  0.235035  0.342939  0.022939  0.267944  0.998837
4  0.175961  0.077481  0.857204  0.101328  0.501221

In [181]:
%timeit df['A'] + df['B'] / df['C']  - df['D'] * df['E']

42.6 ms ± 8.04 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [182]:
%timeit pd.eval("df.A + df.B / df.C  - df.D * df.E")

13.9 ms ± 740 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [183]:
%timeit df.eval('A + B / C - D * E')

28.3 ms ± 10.2 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [184]:
df.eval('R = A + B / C - D * E', inplace=True)
df.head()

A         B         C         D         E          R
0  0.447120  0.704714  0.824506  0.266879  0.145419   1.263021
1  0.570413  0.658671  0.559462  0.884593  0.434366   1.363505
2  0.227988  0.258697  0.012942  0.860729  0.515783  19.772344
3  0.235035  0.342939  0.022939  0.267944  0.998837  14.917764
4  0.175961  0.077481  0.857204  0.101328  0.501221   0.215561

In [185]:
df.eval('R = A - B / C + D * E', inplace=True)
df.head()

A         B         C         D         E          R
0  0.447120  0.704714  0.824506  0.266879  0.145419  -0.368781
1  0.570413  0.658671  0.559462  0.884593  0.434366  -0.222679
2  0.227988  0.258697  0.012942  0.860729  0.515783 -19.316368
3  0.235035  0.342939  0.022939  0.267944  0.998837 -14.447694
4  0.175961  0.077481  0.857204  0.101328  0.501221   0.136360

In [186]:
col_mean = df.mean(1)
df['A'] + col_mean

0         0.783763
1         1.051218
2        -2.678717
3        -1.861632
4         0.484220
            ...   
999995    1.308146
999996    0.763042
999997    0.543293
999998    1.506456
999999    0.960427
Length: 1000000, dtype: float64

In [187]:
df.eval('A + @col_mean') # 외부에 있는 변수도 '@'을 사용하여 불러올 수 있다.

0         0.783763
1         1.051218
2        -2.678717
3        -1.861632
4         0.484220
            ...   
999995    1.308146
999996    0.763042
999997    0.543293
999998    1.506456
999999    0.960427
Length: 1000000, dtype: float64

In [188]:
df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]
# 여러 조건을 포함하는 계산식 경우에도

A         B         C         D         E         R
4       0.175961  0.077481  0.857204  0.101328  0.501221  0.136360
5       0.340390  0.457674  0.592839  0.847194  0.436968 -0.061417
29      0.170630  0.472416  0.599984  0.564127  0.883358 -0.118424
34      0.111860  0.042147  0.925167  0.827847  0.838914  0.760796
35      0.034963  0.373159  0.867096  0.636549  0.152565 -0.298277
...          ...       ...       ...       ...       ...       ...
999972  0.498110  0.056223  0.613394  0.681376  0.792257  0.946275
999982  0.402794  0.162216  0.952417  0.919688  0.094636  0.319510
999985  0.349757  0.498133  0.646916  0.175768  0.418112 -0.346765
999997  0.017773  0.378500  0.636326  0.971556  0.875456  0.273507
999999  0.452461  0.143118  0.984058  0.753203  0.232679  0.482278

[124576 rows x 6 columns]

In [189]:
pd.eval('df[(df.A < 0.5) & (df.B < 0.5) & (df.C > 0.5)]')
# eval로 가능하다.

A         B         C         D         E         R
4       0.175961  0.077481  0.857204  0.101328  0.501221  0.136360
5       0.340390  0.457674  0.592839  0.847194  0.436968 -0.061417
29      0.170630  0.472416  0.599984  0.564127  0.883358 -0.118424
34      0.111860  0.042147  0.925167  0.827847  0.838914  0.760796
35      0.034963  0.373159  0.867096  0.636549  0.152565 -0.298277
...          ...       ...       ...       ...       ...       ...
999972  0.498110  0.056223  0.613394  0.681376  0.792257  0.946275
999982  0.402794  0.162216  0.952417  0.919688  0.094636  0.319510
999985  0.349757  0.498133  0.646916  0.175768  0.418112 -0.346765
999997  0.017773  0.378500  0.636326  0.971556  0.875456  0.273507
999999  0.452461  0.143118  0.984058  0.753203  0.232679  0.482278

[124576 rows x 6 columns]

In [190]:
df.query('(A < 0.5) and (B < 0.5) and (C > 0.5)')
# 조건을 가진 질의문인 경우에도 query를 쓰고 질의문을 쓰면 더 빠른 연산이 가능

A         B         C         D         E         R
4       0.175961  0.077481  0.857204  0.101328  0.501221  0.136360
5       0.340390  0.457674  0.592839  0.847194  0.436968 -0.061417
29      0.170630  0.472416  0.599984  0.564127  0.883358 -0.118424
34      0.111860  0.042147  0.925167  0.827847  0.838914  0.760796
35      0.034963  0.373159  0.867096  0.636549  0.152565 -0.298277
...          ...       ...       ...       ...       ...       ...
999972  0.498110  0.056223  0.613394  0.681376  0.792257  0.946275
999982  0.402794  0.162216  0.952417  0.919688  0.094636  0.319510
999985  0.349757  0.498133  0.646916  0.175768  0.418112 -0.346765
999997  0.017773  0.378500  0.636326  0.971556  0.875456  0.273507
999999  0.452461  0.143118  0.984058  0.753203  0.232679  0.482278

[124576 rows x 6 columns]

In [191]:
col_mean = df['D'].mean()
df[(df.A < col_mean) & (df.B < col_mean)]

A         B         C         D         E          R
2       0.227988  0.258697  0.012942  0.860729  0.515783 -19.316368
3       0.235035  0.342939  0.022939  0.267944  0.998837 -14.447694
4       0.175961  0.077481  0.857204  0.101328  0.501221   0.136360
5       0.340390  0.457674  0.592839  0.847194  0.436968  -0.061417
21      0.136791  0.061636  0.398211  0.932661  0.114501   0.088799
...          ...       ...       ...       ...       ...        ...
999985  0.349757  0.498133  0.646916  0.175768  0.418112  -0.346765
999989  0.155993  0.317534  0.144882  0.178870  0.500458  -1.946163
999992  0.053551  0.384541  0.226994  0.920090  0.594915  -1.093132
999997  0.017773  0.378500  0.636326  0.971556  0.875456   0.273507
999999  0.452461  0.143118  0.984058  0.753203  0.232679   0.482278

[248831 rows x 6 columns]

In [192]:
df.query('A < @col_mean and B < @col_mean')

A         B         C         D         E          R
2       0.227988  0.258697  0.012942  0.860729  0.515783 -19.316368
3       0.235035  0.342939  0.022939  0.267944  0.998837 -14.447694
4       0.175961  0.077481  0.857204  0.101328  0.501221   0.136360
5       0.340390  0.457674  0.592839  0.847194  0.436968  -0.061417
21      0.136791  0.061636  0.398211  0.932661  0.114501   0.088799
...          ...       ...       ...       ...       ...        ...
999985  0.349757  0.498133  0.646916  0.175768  0.418112  -0.346765
999989  0.155993  0.317534  0.144882  0.178870  0.500458  -1.946163
999992  0.053551  0.384541  0.226994  0.920090  0.594915  -1.093132
999997  0.017773  0.378500  0.636326  0.971556  0.875456   0.273507
999999  0.452461  0.143118  0.984058  0.753203  0.232679   0.482278

[248831 rows x 6 columns]

## 데이터 결합

### Concat( ) / Append( )

In [193]:
s1 = pd.Series(['a','b'], index = [1, 2])
s2 = pd.Series(['c','d'], index = [3, 4])
pd.concat([s1, s2])

1    a
2    b
3    c
4    d
dtype: object

In [194]:
def create_df(cols, idx):
    data = {c: [str(c.lower()) + str(i) for i in idx] for c in cols}
    return pd.DataFrame(data, idx)

In [195]:
df1 = create_df('AB', [1, 2])
df1

A   B
1  a1  b1
2  a2  b2

In [196]:
df2 = create_df('AB',[3, 4])
df2

A   B
3  a3  b3
4  a4  b4

In [197]:
pd.concat([df1, df2]) # Index의 기준에 따라 아래로 데이터 테이블이 붙음

A   B
1  a1  b1
2  a2  b2
3  a3  b3
4  a4  b4

In [198]:
df3 = create_df('AB', [0,1])
df3

A   B
0  a0  b0
1  a1  b1

In [199]:
df4 = create_df('CD', [0,1])
df4

C   D
0  c0  d0
1  c1  d1

In [200]:
pd.concat([df3, df4])
# column명을 기준으로 두 DataFrame이 붙지만 
# df3와 df4의 Column명이 다르기 때문에 다른 Column에 대한 value는 NaN으로 처리된다.

A    B    C    D
0   a0   b0  NaN  NaN
1   a1   b1  NaN  NaN
0  NaN  NaN   c0   d0
1  NaN  NaN   c1   d1

In [201]:
pd.concat([df3, df4], axis=1)

A   B   C   D
0  a0  b0  c0  d0
1  a1  b1  c1  d1

In [202]:
pd.concat([df1, df3])

A   B
1  a1  b1
2  a2  b2
0  a0  b0
1  a1  b1

In [203]:
# pd.concat([df1, df3], verify_integrity=True)
# verify_integrity는 결합하는 두 DataFrame의 index에 동일한 값이 있으면 
# 오류를 생성하게 하여 생성을 방지함

In [204]:
pd.concat([df1, df3], ignore_index=True)

A   B
0  a1  b1
1  a2  b2
2  a0  b0
3  a1  b1

In [205]:
pd.concat([df1, df3], keys=['x','y'])
# MultiIndex의 형태로 만들어줌

A   B
x 1  a1  b1
  2  a2  b2
y 0  a0  b0
  1  a1  b1

In [206]:
df5 = create_df('ABC',[1, 2])
df6 = create_df('BCD',[3,4])
pd.concat([df5, df6])

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

In [207]:
pd.concat([df5, df6], join='inner')
# columns 중에 공통된 column만이 결합되어 합쳐짐

B   C
1  b1  c1
2  b2  c2
3  b3  c3
4  b4  c4

In [208]:
df5.append(df6)
# concat과 같은 용도

A   B   C    D
1   a1  b1  c1  NaN
2   a2  b2  c2  NaN
3  NaN  b3  c3   d3
4  NaN  b4  c4   d4

### 병합과 조인

In [209]:
df1 = pd.DataFrame({'학생':['홍길동','이순신','임꺽정','김유신'],
                    '학과':['경영학과','교육학과','컴퓨터학과','통계학과']})
df1

학생     학과
0  홍길동   경영학과
1  이순신   교육학과
2  임꺽정  컴퓨터학과
3  김유신   통계학과

In [210]:
df2 = pd.DataFrame({'학생':['홍길동','이순신','임꺽정','김유신'],
                    '입학년도':[2012, 2016, 2019, 2020]})
df2

학생  입학년도
0  홍길동  2012
1  이순신  2016
2  임꺽정  2019
3  김유신  2020

In [211]:
df3 = pd.merge(df1, df2)
df3

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [212]:
df4 = pd.DataFrame({'학과':['경영학과','교육학과','컴퓨터학과','통계학과'],
                    '학과장':['황희','장영실','안창호','정약용']})
df4

학과  학과장
0   경영학과   황희
1   교육학과  장영실
2  컴퓨터학과  안창호
3   통계학과  정약용

In [213]:
pd.merge(df3, df4)

학생     학과  입학년도  학과장
0  홍길동   경영학과  2012   황희
1  이순신   교육학과  2016  장영실
2  임꺽정  컴퓨터학과  2019  안창호
3  김유신   통계학과  2020  정약용

In [214]:
df5 = pd.DataFrame({'학과':['경영학과','교육학과','교육학과','컴퓨터학과','컴퓨터학과','통계학과'],
                    '과목':['경영개론','기초수학','물리학','프로그래밍','운영체제','확률론']})
df5

학과     과목
0   경영학과   경영개론
1   교육학과   기초수학
2   교육학과    물리학
3  컴퓨터학과  프로그래밍
4  컴퓨터학과   운영체제
5   통계학과    확률론

In [215]:
pd.merge(df1, df5)
# merge하는 기준은 공통된 학과
# df1은 학생/학과라는 컬럼이 있고
# df5는 학과/과목이 존재한다.
# merge를 할 경우 공통된 컬럼인 학과를 기준으로 병합되기 때문에
# df1의 학생의 컬럼이 늘어난다.

학생     학과     과목
0  홍길동   경영학과   경영개론
1  이순신   교육학과   기초수학
2  이순신   교육학과    물리학
3  임꺽정  컴퓨터학과  프로그래밍
4  임꺽정  컴퓨터학과   운영체제
5  김유신   통계학과    확률론

In [216]:
pd.merge(df1, df2, on='학생')

학생     학과  입학년도
0  홍길동   경영학과  2012
1  이순신   교육학과  2016
2  임꺽정  컴퓨터학과  2019
3  김유신   통계학과  2020

In [217]:
df6 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                    '성적':['A','A+','B','A+']})
df6

이름  성적
0  홍길동   A
1  이순신  A+
2  임꺽정   B
3  김유신  A+

In [218]:
pd.merge(df1, df6, left_on='학생', right_on='이름')

학생     학과   이름  성적
0  홍길동   경영학과  홍길동   A
1  이순신   교육학과  이순신  A+
2  임꺽정  컴퓨터학과  임꺽정   B
3  김유신   통계학과  김유신  A+

In [219]:
pd.merge(df1, df6, left_on='학생',right_on='이름').drop('이름',axis=1)

학생     학과  성적
0  홍길동   경영학과   A
1  이순신   교육학과  A+
2  임꺽정  컴퓨터학과   B
3  김유신   통계학과  A+

In [220]:
mdf1 = df1.set_index('학생')
mdf2 = df2.set_index('학생')

In [221]:
mdf1

학과
학생        
홍길동   경영학과
이순신   교육학과
임꺽정  컴퓨터학과
김유신   통계학과

In [222]:
mdf2

입학년도
학생       
홍길동  2012
이순신  2016
임꺽정  2019
김유신  2020

In [223]:
pd.merge(mdf1, mdf2, left_index=True, right_index=True)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [224]:
mdf1.join(mdf2)

학과  입학년도
학생              
홍길동   경영학과  2012
이순신   교육학과  2016
임꺽정  컴퓨터학과  2019
김유신   통계학과  2020

In [225]:
pd.merge(mdf1, df6, left_index=True, right_on='이름')

학과   이름  성적
0   경영학과  홍길동   A
1   교육학과  이순신  A+
2  컴퓨터학과  임꺽정   B
3   통계학과  김유신  A+

In [226]:
df7 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정'],
                    '주문음식':['햄버거','피자','짜장면']})
df7

이름 주문음식
0  홍길동  햄버거
1  이순신   피자
2  임꺽정  짜장면

In [227]:
df8 = pd.DataFrame({'이름':['홍길동','이순신','김유신'],
                     '주문음료':['콜라','사이다','커피']})
df8

이름 주문음료
0  홍길동   콜라
1  이순신  사이다
2  김유신   커피

In [228]:
pd.merge(df7, df8)

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [229]:
pd.merge(df7, df8, how='inner')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다

In [230]:
pd.merge(df7, df8, how='outer')

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN
3  김유신  NaN   커피

In [231]:
pd.merge(df7, df8, how='left')
# df7에 있는 것만 기준으로 병합
# df8에는 없는 것들은 NaN을 반환

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  임꺽정  짜장면  NaN

In [232]:
pd.merge(df7, df8, how='right')
# df8을 기준으로
# df8에 김유신이 있지만 김유신의 주문음식은 존재하지 않는다.
# df7에는 임꺽정이 있지만 df8을 기준으로 하기 때문에 나타나지 않는다.

이름 주문음식 주문음료
0  홍길동  햄버거   콜라
1  이순신   피자  사이다
2  김유신  NaN   커피

In [233]:
df9 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                    '순위':[3, 2, 4, 1]})
df9

이름  순위
0  홍길동   3
1  이순신   2
2  임꺽정   4
3  김유신   1

In [234]:
df10 = pd.DataFrame({'이름':['홍길동','이순신','임꺽정','김유신'],
                    '순위':[4, 1, 3, 2]})
df10

이름  순위
0  홍길동   4
1  이순신   1
2  임꺽정   3
3  김유신   2

In [235]:
pd.merge(df9, df10, on='이름')

이름  순위_x  순위_y
0  홍길동     3     4
1  이순신     2     1
2  임꺽정     4     3
3  김유신     1     2

In [236]:
pd.merge(df9, df10, on='이름', suffixes=["_인기","_성적"])

이름  순위_인기  순위_성적
0  홍길동      3      4
1  이순신      2      1
2  임꺽정      4      3
3  김유신      1      2

## 데이터 집계와 그룹 연산

### 집계 연산(Aggregation)

|집계|설명|
|:--|:--|
|```count```|전체 갯수|
|```head, tail```|앞의 항목 일부 반환, 뒤의 항목 일부 반환|
|```describe```|Series, DataFrame의 각 컬럼에 대한 요약 통계|
|```min, max```|최소값, 최대값|
|```cummin, cummax```|누적 최소값, 누적 최대값|
|```argmin, argmax```|최소값과 최대값의 색인 위치|
|```idxmin, idxmax```|최소값과 최대값의 색인값|
|```mean, median```|평균값, 중앙값|
|```std, var```|표준편차, 분산|
|```skew```|왜도 값 계산|
|```kurt```|첨도 값 계산|
|```mad```|절대 평균 편차|
|```sum, cusum```|전체 항목 합, 누적합|
|```prod, cumprod```|전체 항목 곱, 누적곱|
|```quatile```|0부터 1까지의 분위수 계산|
|```diff```|1차 산술차 계산|
|```pct_change```|퍼센트 변화율 계산|
|```corr, cov```|상관관계, 공분산 계산|

In [239]:
df = pd.DataFrame([[1, 1.2, np.nan], 
                  [2.4, 5.5, 4.2],
                  [np.nan, np.nan, np.nan],
                  [0.44, -3.1, 4.1]],
                  index=[1, 2, 3, 4],
                  columns = ['A','B','C'])
df

A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1  4.1

In [240]:
df.head(2)

A    B    C
1  1.0  1.2  NaN
2  2.4  5.5  4.2

In [241]:
df.tail(2)

A    B    C
3   NaN  NaN  NaN
4  0.44 -3.1  4.1

In [242]:
df.describe()

A     B         C
count  3.000000  3.00  2.000000
mean   1.280000  1.20  4.150000
std    1.009554  4.30  0.070711
min    0.440000 -3.10  4.100000
25%    0.720000 -0.95  4.125000
50%    1.000000  1.20  4.150000
75%    1.700000  3.35  4.175000
max    2.400000  5.50  4.200000

In [243]:
print(df)
print(np.argmin(df), np.argmax(df))

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1  4.1
2 2


In [244]:
print(df)
print(df.idxmin())
print(df.idxmax())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1  4.1
A    4
B    4
C    4
dtype: int64
A    2
B    2
C    2
dtype: int64


In [246]:
print(df)
print(df.std())
print(df.var())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1  4.1
A    1.009554
B    4.300000
C    0.070711
dtype: float64
A     1.0192
B    18.4900
C     0.0050
dtype: float64


In [248]:
print(df)
print(df.skew())
print(df.kurt())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1  4.1
A    1.15207
B    0.00000
C        NaN
dtype: float64
A   NaN
B   NaN
C   NaN
dtype: float64


In [249]:
print(df)
print(df.sum())
print(df.cumsum())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1  4.1
A    3.84
B    3.60
C    8.30
dtype: float64
      A    B    C
1  1.00  1.2  NaN
2  3.40  6.7  4.2
3   NaN  NaN  NaN
4  3.84  3.6  8.3


In [250]:
print(df)
print(df.prod())
print(df.cumprod())

      A    B    C
1  1.00  1.2  NaN
2  2.40  5.5  4.2
3   NaN  NaN  NaN
4  0.44 -3.1  4.1
A     1.056
B   -20.460
C    17.220
dtype: float64
       A      B      C
1  1.000   1.20    NaN
2  2.400   6.60   4.20
3    NaN    NaN    NaN
4  1.056 -20.46  17.22


In [251]:
df.diff()

A    B   C
1  NaN  NaN NaN
2  1.4  4.3 NaN
3  NaN  NaN NaN
4  NaN  NaN NaN

In [252]:
df.quantile()

A    1.00
B    1.20
C    4.15
Name: 0.5, dtype: float64

In [253]:
df.pct_change()

A         B        C
1       NaN       NaN      NaN
2  1.400000  3.583333      NaN
3  0.000000  0.000000  0.00000
4 -0.816667 -1.563636 -0.02381

In [254]:
df.corr()

A         B    C
A  1.000000  0.970725  1.0
B  0.970725  1.000000  1.0
C  1.000000  1.000000  1.0

In [256]:
df.corrwith(df.B)

A    0.970725
B    1.000000
C    1.000000
dtype: float64

In [257]:
df.cov()

A       B      C
A  1.0192   4.214  0.098
B  4.2140  18.490  0.430
C  0.0980   0.430  0.005

In [258]:
df.B.unique()

array([ 1.2,  5.5,  nan, -3.1])

In [259]:
df.A.value_counts()

2.40    1
0.44    1
1.00    1
Name: A, dtype: int64

### GroupBy 연산

In [260]:
df = pd.DataFrame({'c1':['a','a','b','b','c','d','b'],
                   'c2':['A','B','B','A','D','C','C'],
                   'c3':np.random.randint(7), 
                   'c4':np.random.random(7)})
df

c1 c2  c3        c4
0  a  A   6  0.019950
1  a  B   6  0.460974
2  b  B   6  0.986288
3  b  A   6  0.839825
4  c  D   6  0.304955
5  d  C   6  0.084530
6  b  C   6  0.273144

In [261]:
df.dtypes

c1     object
c2     object
c3      int64
c4    float64
dtype: object

In [263]:
df['c3'].groupby(df['c1']).mean()
# c3에 대한 값을 c1을 기준으로 groupby하여 평균값을 내겠다.

c1
a    6
b    6
c    6
d    6
Name: c3, dtype: int64

In [264]:
df['c4'].groupby(df['c2']).std()

c2
A    0.579739
B    0.371453
C    0.133370
D         NaN
Name: c4, dtype: float64

In [267]:
df['c4'].groupby([df['c1'], df['c2']]).mean()

c1  c2
a   A     0.019950
    B     0.460974
b   A     0.839825
    B     0.986288
    C     0.273144
c   D     0.304955
d   C     0.084530
Name: c4, dtype: float64

In [269]:
df['c4'].groupby([df['c1'], df['c2']]).mean().unstack()

c2         A         B         C         D
c1                                        
a   0.019950  0.460974       NaN       NaN
b   0.839825  0.986288  0.273144       NaN
c        NaN       NaN       NaN  0.304955
d        NaN       NaN  0.084530       NaN

In [270]:
df['c4'].groupby([df['c1'], df['c2']]).mean().to_frame()

c4
c1 c2          
a  A   0.019950
   B   0.460974
b  A   0.839825
   B   0.986288
   C   0.273144
c  D   0.304955
d  C   0.084530

In [271]:
df.groupby('c1').mean()
# 전체 값을 모두 구하고 싶을때

c3        c4
c1              
a    6  0.240462
b    6  0.699752
c    6  0.304955
d    6  0.084530

In [272]:
df.groupby(['c1','c2']).mean()

c3        c4
c1 c2              
a  A    6  0.019950
   B    6  0.460974
b  A    6  0.839825
   B    6  0.986288
   C    6  0.273144
c  D    6  0.304955
d  C    6  0.084530

In [273]:
df.groupby(['c1','c2']).size()

c1  c2
a   A     1
    B     1
b   A     1
    B     1
    C     1
c   D     1
d   C     1
dtype: int64

In [274]:
for c1, group in df.groupby('c1'):
    print(c1)
    print(group)

a
  c1 c2  c3        c4
0  a  A   6  0.019950
1  a  B   6  0.460974
b
  c1 c2  c3        c4
2  b  B   6  0.986288
3  b  A   6  0.839825
6  b  C   6  0.273144
c
  c1 c2  c3        c4
4  c  D   6  0.304955
d
  c1 c2  c3       c4
5  d  C   6  0.08453


In [277]:
for (c1, c2) in df.groupby(['c1', 'c2']):
    print((c1, c2), end='\n')
    print(group)

(('a', 'A'),   c1 c2  c3       c4
0  a  A   6  0.01995)
  c1 c2  c3       c4
5  d  C   6  0.08453
(('a', 'B'),   c1 c2  c3        c4
1  a  B   6  0.460974)
  c1 c2  c3       c4
5  d  C   6  0.08453
(('b', 'A'),   c1 c2  c3        c4
3  b  A   6  0.839825)
  c1 c2  c3       c4
5  d  C   6  0.08453
(('b', 'B'),   c1 c2  c3        c4
2  b  B   6  0.986288)
  c1 c2  c3       c4
5  d  C   6  0.08453
(('b', 'C'),   c1 c2  c3        c4
6  b  C   6  0.273144)
  c1 c2  c3       c4
5  d  C   6  0.08453
(('c', 'D'),   c1 c2  c3        c4
4  c  D   6  0.304955)
  c1 c2  c3       c4
5  d  C   6  0.08453
(('d', 'C'),   c1 c2  c3       c4
5  d  C   6  0.08453)
  c1 c2  c3       c4
5  d  C   6  0.08453


In [279]:
df.groupby(['c1','c2'])[['c4']].mean()

c4
c1 c2          
a  A   0.019950
   B   0.460974
b  A   0.839825
   B   0.986288
   C   0.273144
c  D   0.304955
d  C   0.084530

In [280]:
df.groupby('c1')['c3'].quantile()

c1
a    6.0
b    6.0
c    6.0
d    6.0
Name: c3, dtype: float64

In [281]:
df.groupby('c1')['c3'].count()

c1
a    2
b    3
c    1
d    1
Name: c3, dtype: int64

In [282]:
df.groupby('c1')['c4'].median()

c1
a    0.240462
b    0.839825
c    0.304955
d    0.084530
Name: c4, dtype: float64

In [283]:
df.groupby('c1')['c4'].std()

c1
a    0.311851
b    0.376642
c         NaN
d         NaN
Name: c4, dtype: float64

In [284]:
df.groupby(['c1','c2'])['c4'].agg(['mean','min','max'])

mean       min       max
c1 c2                              
a  A   0.019950  0.019950  0.019950
   B   0.460974  0.460974  0.460974
b  A   0.839825  0.839825  0.839825
   B   0.986288  0.986288  0.986288
   C   0.273144  0.273144  0.273144
c  D   0.304955  0.304955  0.304955
d  C   0.084530  0.084530  0.084530

In [285]:
df.groupby(['c1','c2'], as_index=False)['c4'].mean()

c1 c2        c4
0  a  A  0.019950
1  a  B  0.460974
2  b  A  0.839825
3  b  B  0.986288
4  b  C  0.273144
5  c  D  0.304955
6  d  C  0.084530

In [286]:
df.groupby(['c1','c2'])['c4'].mean()

c1  c2
a   A     0.019950
    B     0.460974
b   A     0.839825
    B     0.986288
    C     0.273144
c   D     0.304955
d   C     0.084530
Name: c4, dtype: float64

In [287]:
df.groupby(['c1','c2'], group_keys=False)['c4'].mean()

c1  c2
a   A     0.019950
    B     0.460974
b   A     0.839825
    B     0.986288
    C     0.273144
c   D     0.304955
d   C     0.084530
Name: c4, dtype: float64

In [290]:
def top(df, n=3, column='c1'):
    return df.sort_values(by=column)[-n:]

top(df, n=5)

c1 c2  c3        c4
2  b  B   6  0.986288
3  b  A   6  0.839825
6  b  C   6  0.273144
4  c  D   6  0.304955
5  d  C   6  0.084530

In [291]:
df.groupby('c1').apply(top)

c1 c2  c3        c4
c1                      
a  0  a  A   6  0.019950
   1  a  B   6  0.460974
b  2  b  B   6  0.986288
   3  b  A   6  0.839825
   6  b  C   6  0.273144
c  4  c  D   6  0.304955
d  5  d  C   6  0.084530

### 피벗 테이블 (Pivot Table)
|함수|설명|
|:-|:-|
|```values```|집계하려는 컬럼 이름 혹은 이름의 리스트. 기본적으로 모든 숫자 컬럼 집계|
|```index```|피벗테이블의 로우를 그룹으로 묶을 컬럼 이름이나 그룹 키|
|```columns```|피벗테이블의 컬럼을 그룹으로 묶을 컬럼 이름이나 그룹 키|
|```aggfunc```|집계 함수나 함수 리스트. 기본값으로 ```mean```이 사용|
|```fil_value```|결과 테이블에서 누락된 값 대체를 위한 값|
|```dropna```|True인 경우 모든 항목이 NA인 컬럼은 포함하지 않음|
|```margins```|부분 합이나 총계를 담기 위한 로우/컬럼 추가 여부. 기본값은 False|

In [292]:
df.pivot_table(['c3','c4'],
               index=['c1'],
               columns=['c2'])

c3                       c4                              
c2    A    B    C    D         A         B         C         D
c1                                                            
a   6.0  6.0  NaN  NaN  0.019950  0.460974       NaN       NaN
b   6.0  6.0  6.0  NaN  0.839825  0.986288  0.273144       NaN
c   NaN  NaN  NaN  6.0       NaN       NaN       NaN  0.304955
d   NaN  NaN  6.0  NaN       NaN       NaN  0.084530       NaN

In [293]:
df.pivot_table(['c3','c4'],
               index=['c1'],
               columns=['c2'],
               margins=True)

c3                           c4                                        
c2     A    B    C    D All         A         B         C         D       All
c1                                                                           
a    6.0  6.0  NaN  NaN   6  0.019950  0.460974       NaN       NaN  0.240462
b    6.0  6.0  6.0  NaN   6  0.839825  0.986288  0.273144       NaN  0.699752
c    NaN  NaN  NaN  6.0   6       NaN       NaN       NaN  0.304955  0.304955
d    NaN  NaN  6.0  NaN   6       NaN       NaN  0.084530       NaN  0.084530
All  6.0  6.0  6.0  6.0   6  0.429887  0.723631  0.178837  0.304955  0.424238

In [294]:
df.pivot_table(['c3','c4'],
               index=['c1'],
               columns=['c2'],
               margins=True,
               aggfunc=sum)

c3                             c4                                \
c2      A     B     C    D All         A         B         C         D   
c1                                                                       
a     6.0   6.0   NaN  NaN  12  0.019950  0.460974       NaN       NaN   
b     6.0   6.0   6.0  NaN  18  0.839825  0.986288  0.273144       NaN   
c     NaN   NaN   NaN  6.0   6       NaN       NaN       NaN  0.304955   
d     NaN   NaN   6.0  NaN   6       NaN       NaN  0.084530       NaN   
All  12.0  12.0  12.0  6.0  42  0.859775  1.447262  0.357674  0.304955   

               
c2        All  
c1             
a    0.480924  
b    2.099257  
c    0.304955  
d    0.084530  
All  2.969666

In [295]:
df.pivot_table(['c3','c4'],
               index=['c1'],
               columns=['c2'],
               margins=True,
               aggfunc=sum,
               fill_value=0)

c3                       c4                                        
c2    A   B   C  D All         A         B         C         D       All
c1                                                                      
a     6   6   0  0  12  0.019950  0.460974  0.000000  0.000000  0.480924
b     6   6   6  0  18  0.839825  0.986288  0.273144  0.000000  2.099257
c     0   0   0  6   6  0.000000  0.000000  0.000000  0.304955  0.304955
d     0   0   6  0   6  0.000000  0.000000  0.084530  0.000000  0.084530
All  12  12  12  6  42  0.859775  1.447262  0.357674  0.304955  2.969666

In [296]:
pd.crosstab(df.c1, df.c2)

c2  A  B  C  D
c1            
a   1  1  0  0
b   1  1  1  0
c   0  0  0  1
d   0  0  1  0

In [297]:
pd.crosstab(df.c1, df.c2, values=df.c3, aggfunc=sum, margins=True)

c2      A     B     C    D  All
c1                             
a     6.0   6.0   NaN  NaN   12
b     6.0   6.0   6.0  NaN   18
c     NaN   NaN   NaN  6.0    6
d     NaN   NaN   6.0  NaN    6
All  12.0  12.0  12.0  6.0   42

### 범주형(Categorical) 데이터
<br>
- 성능을 향상시키기 위한 데이터 유형
<br>  
<br>

|메소드|설명|
|:--|:--|
|```add_categories```|기존 카테고리에 새로운 카테고리 추가|
|```as_ordered```|카테고리에 순서 지정|
|```as_unordered```|카테고리에 순서 미지정|
|```remove_categories```|카테고리 제거|
|```remove_unused_categories```|사용하지 않는 카테고리 제거|
|```rename_categories```|카테고리 이름 변경|
|```reorder_categories```|새로운 카테고리에 순서 지정|
|```set_categories```|새로운 카테고리로 변경|

In [298]:
s = pd.Series(['c1','c2','c1','c2','c1']*2)
s

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
dtype: object

In [299]:
pd.unique(s)

array(['c1', 'c2'], dtype=object)

In [300]:
pd.value_counts(s)

c1    6
c2    4
dtype: int64

In [301]:
code = pd.Series([0,1,0,1,0] * 2)
code

0    0
1    1
2    0
3    1
4    0
5    0
6    1
7    0
8    1
9    0
dtype: int64

In [302]:
d = pd.Series(['c1','c2'])
d

0    c1
1    c2
dtype: object

In [303]:
d.take(code)

0    c1
1    c2
0    c1
1    c2
0    c1
0    c1
1    c2
0    c1
1    c2
0    c1
dtype: object

In [304]:
df = pd.DataFrame({'id': np.arange(len(s)),
                   'c':s, 
                   'v':np.random.randint(1000,5000, size=len(s))})
df

id   c     v
0   0  c1  3030
1   1  c2  4331
2   2  c1  1683
3   3  c2  4690
4   4  c1  3889
5   5  c1  4293
6   6  c2  1989
7   7  c1  4169
8   8  c2  4215
9   9  c1  4346

In [305]:
c = df['c'].astype('category')
c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [306]:
c.values

['c1', 'c2', 'c1', 'c2', 'c1', 'c1', 'c2', 'c1', 'c2', 'c1']
Categories (2, object): ['c1', 'c2']

In [307]:
c.values.categories

Index(['c1', 'c2'], dtype='object')

In [309]:
c.values.codes

array([0, 1, 0, 1, 0, 0, 1, 0, 1, 0], dtype=int8)

In [310]:
df['c'] = c
df.c

0    c1
1    c2
2    c1
3    c2
4    c1
5    c1
6    c2
7    c1
8    c2
9    c1
Name: c, dtype: category
Categories (2, object): ['c1', 'c2']

In [311]:
c = pd.Categorical(['c1','c2', 'c3','c1','c2'])
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [323]:
categories = ['c1','c2','c3']
code = [0, 1, 2, 0, 1]
c = pd.Categorical.from_codes(codes, categories)
c

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1', 'c2', 'c3']

In [324]:
pd.Categorical.from_codes(codes, categories, ordered=True)

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [325]:
c.as_ordered()

['c1', 'c2', 'c3', 'c1', 'c2']
Categories (3, object): ['c1' < 'c2' < 'c3']

In [326]:
c.codes

array([0, 1, 2, 0, 1], dtype=int8)

In [316]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

In [328]:
c = c.set_categories(['c1','c2','c3','c4','c5'])
c.categories

Index(['c1', 'c2', 'c3', 'c4', 'c5'], dtype='object')

In [329]:
c.value_counts()

c1    2
c2    2
c3    1
c4    0
c5    0
dtype: int64

In [330]:
c[c.isin(['c1','c3'])]

['c1', 'c3', 'c1']
Categories (5, object): ['c1', 'c2', 'c3', 'c4', 'c5']

In [331]:
c = c.remove_unused_categories()

In [332]:
c.categories

Index(['c1', 'c2', 'c3'], dtype='object')

## 문자열 연산

In [ ]:
# 2:50:23