In [2]:
import pandas as pd
import numpy as np

# 1. Write a Pandas program to create and display a one-dimensional array-like

In [3]:
example = np.array([1, 4, 3, 5, 8])
example

array([1, 4, 3, 5, 8])

# 2. Write a Pandas program to convert a Panda module Series to Python list and it's type.

In [6]:
toseries = [1, 2, 3, 4, 5]
toseries = pd.Series(toseries)

example2 = pd.Series([1, 2, 3, 4, 5])
tolist = example2.tolist()

print(type(tolist))
print(type(toseries))

tolist

<class 'list'>
<class 'pandas.core.series.Series'>


[1, 2, 3, 4, 5]

# 3. Write a Pandas program to add, subtract, multiple and divide two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [18]:
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

series1+series2

0     3
1     7
2    11
3    15
4    19
dtype: int64

In [17]:
series1-series2

0    1
1    1
2    1
3    1
4    1
dtype: int64

In [16]:
series1*series2

0     2
1    12
2    30
3    56
4    90
dtype: int64

In [15]:
series1/series2

0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

# 4. Write a Pandas program to compare the elements of the two Pandas Series.
Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 10]

In [19]:
series1 = pd.Series([2, 4, 6, 8, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

series1 > series2

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [20]:
series1 < series2

0    False
1    False
2    False
3    False
4    False
dtype: bool

In [21]:
series1 >= series2

0    True
1    True
2    True
3    True
4    True
dtype: bool

In [22]:
series1 <= series2

0    False
1    False
2    False
3    False
4    False
dtype: bool

# 5. Write a Pandas program to convert a dictionary to a Pandas series.
Sample Series:  
  
Original dictionary:  
{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}   
  
Converted series:    
a 100    
b 200    
c 300    
d 400    
e 800    
dtype: int64


In [71]:
series = pd.Series({'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800})
series

a    100
b    200
c    300
d    400
e    800
dtype: int64

# 6. Write a Pandas program to convert a NumPy array to a Pandas series.
Sample Series:

NumPy array:
[10 20 30 40 50]

Converted Pandas series:    
0 10    
1 20    
2 30    
3 40    
4 50    
dtype: int64

In [33]:
Toseries = np.array([10, 20, 30, 40,50], int)
Toseries = pd.Series(Toseries, dtype = 'int64')
Toseries

0    10
1    20
2    30
3    40
4    50
dtype: int64

# 7. Write a Pandas program to change the data type of given a column or a Series.
Sample Series:
<br>
<br>
  

Original Data Series:    
0 100    
1 200    
2 python    
3 300.12    
4 400    
dtype: object  
<br>
Change the said data type to numeric:    
0 100.00    
1 200.00    
2 NaN    
3 300.12    
4 400.00    
dtype: float64

In [37]:
originalData=pd.Series([0, 200, 'python', 300.12, 400], dtype='object')
originalData

0         0
1       200
2    python
3    300.12
4       400
dtype: object

In [45]:
originalData[2] = np.nan
originalData.astype('float64')

0      0.00
1    200.00
2       NaN
3    300.12
4    400.00
dtype: float64

# 8. Write a Pandas program to convert the first column of a DataFrame as a Series.
Sample Output:
<br>
<br>
Original DataFrame    
col1 col2 col3    
0 1 4 7    
1 2 5 5    
2 3 6 8    
3 4 9 12    
4 7 5 1     
5 11 0 11
<br>
<br>
1st column as a Series:    
0 1    
1 2    
2 3    
3 4    
4 7    
5 11    
Name: col1, dtype: int64    
<class 'pandas.core.series.Series'>

In [47]:
originalDataframe = pd.DataFrame({'col1':[1, 2, 3, 4, 7, 11],
                                  'col2':[4, 5, 6, 9, 5, 0],
                                  'col3':[7, 5, 8, 12, 1, 11]})
originalDataframe

col1  col2  col3
0     1     4     7
1     2     5     5
2     3     6     8
3     4     9    12
4     7     5     1
5    11     0    11

In [49]:
series = originalDataframe.col1
series

0     1
1     2
2     3
3     4
4     7
5    11
Name: col1, dtype: int64

# 9. Write a Pandas program to convert a given Series to an array.
Sample Output:
<br>
<br>

Original Data Series:    
0 100    
1 200    
2 python    
3 300.12    
4 400    
dtype: object  
<br>
<br>

Series to an array    
['100' '200' 'python' '300.12' '400']

In [50]:
originalDataSeries = pd.Series([100, 200, 'python',300.12, 400], dtype='object')
originalDataSeries

0       100
1       200
2    python
3    300.12
4       400
dtype: object

In [54]:
changeArray = np.array(originalDataSeries, dtype='object')
changeArray

array([100, 200, 'python', 300.12, 400], dtype=object)

# 10. Write a Pandas program to convert Series of lists to one Series.
Sample Output:
<br>
<br>

Original Series of list    
0 [Red, Green, White]    
1 [Red, Black]    
2 [Yellow]    
dtype: object
<br>
<br>

One Series    
0 Red    
1 Green    
2 White    
3 Red    
4 Black    
5 Yellow    
dtype: object

In [73]:
series = pd.Series([['Red','Green','White'],['Red','Black'],['Yellow']])
series

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [74]:
tmp = []
for i in series:
    for z in i:
        tmp.append(z)
answer = pd.Series(tmp)
answer

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

# 11. Write a Pandas program to sort a given Series.
Sample Output:

Original Data Series:  
0 100    
1 200    
2 python    
3 300.12    
4 400    
dtype: object   

0 100    
1 200    
3 300.12    
4 400    
2 python    
dtype: object

In [84]:
series = pd.Series(['100', '200', 'python','300.12', '400'], dtype='object')
series.sort_values()

0       100
1       200
3    300.12
4       400
2    python
dtype: object

# 12. Write a Pandas program to add some data to an existing Series.
Sample Output:

Original Data Series:    
0 100    
1 200    
2 python    
3 300.12    
4 400    
dtype: object    

Data Series after adding some data:    
0 100    
1 200    
2 python    
3 300.12    
4 400    
0 500    
1 php    
dtype: object

In [88]:
series = pd.Series(['100', '200', 'python','300.12', '400'], dtype='object')
series1 = pd.Series(['500','php'])
pd.concat([series,series1], axis=0)

0       100
1       200
2    python
3    300.12
4       400
0       500
1       php
dtype: object

# 13. Write a Pandas program to create a subset of a given series based on value and condition.
Sample Output:

Original Data Series:    
0 0    
1 1    
2 2    
3 3    
4 4    
5 5    
6 6    
7 7    
8 8    
9 9    
10 10    
dtype: int64    

Subset of the above Data Series:    
0 0    
1 1    
2 2    
3 3    
4 4    
5 5    
dtype: int64

# 14. Write a Pandas program to change the order of index of a given series.
Sample Output:

Original Data Series:    
A 1    
B 2    
C 3    
D 4    
E 5    
dtype: int64    

Data Series after changing the order of index:    
B 2    
A 1    
C 3    
D 4    
E 5    
dtype: int64

# 15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.
Sample Output:    
Original Data Series:    
0 1    
1 2    
2 3    
3 4    
4 5    
5 6    
6 7    
7 8    
8 9    
9 5    
10 3    
dtype: int64    

Mean of the said Data Series:    
4.818181818181818    

Standard deviation of the said Data Series:    
2.522624895547565

# 16. Write a Pandas program to get the items of a given series not present in another given series.
Sample Output:

Original Series:    
sr1:    
0 1    
1 2    
2 3    
3 4    
4 5    
dtype: int64    

sr2:    
0 2    
1 4    
2 6    
3 8    
4 10    
dtype: int64    

Items of sr1 not present in sr2:    
0 1    
2 3    
4 5    
dtype: int64

# ★ 17. Write a Pandas program to get the items which are not common of two given series.
Sample Output:

Original Series:    
sr1:    
0 1    
1 2    
2 3    
3 4    
4 5    
dtype: int64    

sr2:    
0 2    
1 4    
2 6    
3 8    
4 10    
dtype: int64    

Items of a given series not present in another given series:    
0 1    
2 3    
4 5    
5 6    
6 8    
7 10    
dtype: int64

# 18. Write a Pandas program to compute the minimum, 25th percentile, median, 75th, and maximum of a given series.
Sample Output:

Original Series:    
0 3.000938    
1 11.370722    
2 14.612143    
3 8.990256    
4 13.925283    
5 12.056875    
.... 17 14.118931    
18 8.247458    
19 5.526727    
dtype: float64   


Minimum, 25th percentile, median, 75th, and maximum of a given series:    

[ 3.00093811 8.09463867 10.23353705 12.21537733 14.61214321]

# 19. Write a Pandas program to calculate the frequency counts of each unique value of a given series.
Sample Output:

Original Series:    
0 1    
1 7    
2 1    
3 6    
4 9    
5 1    
... 29 2    
30 9    
31 1    
32 2    
33 9    
34 2    
35 9    
36 0    
37 0    
38 4    
39 8    
dtype: object    

Frequency of each unique value of the said series.    
0 9    
2 7    
9 6    
1 5    
6 3    
8 3    
7 3    
3 2    
4 1    
5 1    
dtype: int64

# 20. Write a Pandas program to display most frequent value in a given series and replace everything else as 'Other' in the series.
Sample Output:

Original Series:    
0 3    
1 1    
2 1    
3 3    
4 2    
5 2    
6 1    
7 2    
8 3    
9 1    
10 2    
11 2    
12 2    
13 3    
14 3    
dtype: int64    

Top 2 Freq: 
2 6    
3 5    
1 4    
dtype: int64    
0 Other    
1 Other    
2 Other    
3 Other    
4 2    
5 2    
6 Other    
7 2    
8 Other    
9 Other    
10 2    
11 2    
12 2    
13 Other    
14 Other    

dtype: object